version: "1.0"
services:
  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
    stdin_open: true
    tty: true
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: hopfencraft
    ports:
      - 5432:5432
  email:
    image: maildev/maildev
    ports:
      - 1025:1025
      - 1080:1080
  backend:
    build: ./backend/
    depends_on:
      - db 
      - email
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - GITHUB_CLIENT=${GITHUB_CLIENT}
      - GITHUB_SECRET=${GITHUB_SECRET}
      - GOOGLE_CLIENT=${GOOGLE_CLIENT}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - PAYPAL_CLIENT_ID=${PAYPAL_CLIENT_ID}
      - PAYPAL_CLIENT_SECRET=${PAYPAL_CLIENT_SECRET}
      - RSA_PRIVATE_EXPONENT=${RSA_PRIVATE_EXPONENT}
      - RSA_PRIVATE_MODULUS=${RSA_PRIVATE_MODULUS}
      - RSA_PUBLIC_EXPONENT=${RSA_PUBLIC_EXPONENT}
      - RSA_PUBLIC_MODULUS=${RSA_PUBLIC_MODULUS}
      - UPLOAD_FOLDER_PATH=${UPLOAD_FOLDER_PATH}
