server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: ${DB_PASSWORD}
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  devtools:
    restart:
      enabled: true