server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: psql123
    url: jdbc:postgresql://localhost:5432/hopfencraft
    username: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  devtools:
    restart:
      enabled: true