name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: prod
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: hopfencraft
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    - uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: temurin
        cache: gradle
    - name: Build with Gradle
      working-directory: backend
      run: ./gradlew build
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        GITHUB_CLIENT: ${{ secrets.GHUB_CLIENT }}
        GITHUB_SECRET: ${{ secrets.GHUB_SECRET }}
        GOOGLE_CLIENT: ${{ secrets.GOOGLE_CLIENT }}
        GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
        JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
        PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
        PAYPAL_CLIENT_SECRET: ${{ secrets.PAYPAL_CLIENT_SECRET }}
        RSA_PRIVATE_EXPONENT: ${{ secrets.RSA_PRIVATE_EXPONENT }}
        RSA_PRIVATE_MODULUS: ${{ secrets.RSA_PRIVATE_MODULUS }}
        RSA_PUBLIC_EXPONENT: ${{ secrets.RSA_PUBLIC_EXPONENT }}
        RSA_PUBLIC_MODULUS: ${{ secrets.RSA_PUBLIC_MODULUS }}
        UPLOAD_FOLDER_PATH: ${{ secrets.UPLOAD_FOLDER_PATH }}
        POSTGRES_HOST: localhost    
        POSTGRES_PORT: 5432
    - name: Archive test report
      working-directory: backend
      uses: actions/upload-artifact@v4
      with:
        name: Test report
        path: build/reports/tests/test
