# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Set Environment Variables
       run: |
          echo "VAR1=${{ secrets.DATABASE_URL }}" >> $DATABASE_URL
          echo "VAR2=${{ secrets.DB_PASSWORD }}" >> $DB_PASSWORD
          echo "VAR2=${{ secrets.DB_USERNAME }}" >> $DB_USERNAME
          echo "VAR2=${{ secrets.EMAIL_HOST }}" >> $EMAIL_HOST
          echo "VAR2=${{ secrets.EMAIL_PASSWORD }}" >> $EMAIL_PASSWORD
          echo "VAR2=${{ secrets.EMAIL_PORT }}" >> $EMAIL_PORT
          echo "VAR2=${{ secrets.EMAIL_USERNAME }}" >> $EMAIL_USERNAME
          echo "VAR2=${{ secrets.GHUB_CLIENT }}" >> $GITHUB_CLIENT
          echo "VAR2=${{ secrets.GHUB_SECRET }}" >> $GITHUB_SECRET
          echo "VAR2=${{ secrets.GOOGLE_CLIENT }}" >> $GOOGLE_CLIENT
          echo "VAR2=${{ secrets.GOOGLE_SECRET }}" >> $GOOGLE_SECRET
          echo "VAR2=${{ secrets.JWT_SIGNING_KEY }}" >> $JWT_SIGNING_KEY
          echo "VAR2=${{ secrets.PAYPAL_CLIENT_ID }}" >> $PAYPAL_CLIENT_ID
          echo "VAR2=${{ secrets.PAYPAL_CLIENT_SECRET }}" >> $PAYPAL_CLIENT_SECRET
          echo "VAR2=${{ secrets.RSA_PRIVATE_EXPONENT }}" >> $RSA_PRIVATE_EXPONENT
          echo "VAR2=${{ secrets.RSA_PRIVATE_MODULUS }}" >> $RSA_PRIVATE_MODULUS
          echo "VAR2=${{ secrets.RSA_PUBLIC_EXPONENT }}" >> $RSA_PUBLIC_EXPONENT
          echo "VAR2=${{ secrets.RSA_PUBLIC_MODULUS }}" >> $RSA_PUBLIC_MODULUS
          echo "VAR2=${{ secrets.UPLOAD_FOLDER_PATH }}" >> $UPLOAD_FOLDER_PATH
      
    - name: Build with Maven
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        GITHUB_CLIENT: ${{ secrets.GHUB_CLIENT }}
        GITHUB_SECRET: ${{ secrets.GHUB_SECRET }}
        GOOGLE_CLIENT: ${{ secrets.GOOGLE_CLIENT }}
        GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
        JWT_SIGNING_KEY: ${{ secrets.JWT_SIGNING_KEY }}
        PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
        PAYPAL_CLIENT_SECRET: ${{ secrets.PAYPAL_CLIENT_SECRET }}
        RSA_PRIVATE_EXPONENT: ${{ secrets.RSA_PRIVATE_EXPONENT }}
        RSA_PRIVATE_MODULUS: ${{ secrets.RSA_PRIVATE_MODULUS }}
        RSA_PUBLIC_EXPONENT: ${{ secrets.RSA_PUBLIC_EXPONENT }}
        RSA_PUBLIC_MODULUS: ${{ secrets.RSA_PUBLIC_MODULUS }}
        UPLOAD_FOLDER_PATH: ${{ secrets.UPLOAD_FOLDER_PATH }}
      run: mvn verify -f backend/pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
